paths:
  dependencies:
    conda_env: deeptools-pipeline
data:
  base_path: /cluster/projects/scottgroup/people/lucas/deeptools-pipeline
  cohorts:
    group1:
      # this would really depend on what I wanted to show. you can group by condition (histone mark) or by sample type (plasma, media, ENCODE). 
      # you might need to also seperate based on the how but if a window size that you want too! ex 1 kb vs 10kb, it wil change this for every data type in compute matrix
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/test.csv"
      active: F
      settings:
        bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/1HG38_TSS+TES_ProteinCodingGenes.bed"
        bamCoverage_code: "bamCoverage"
        computeMatrix_code: "computeMatrix reference-point"
        plot_command: "-colorMap Blues"
        identifier: "yo"
    group2:
      # this would really depend on what I wanted to show. you can group by condition (histone mark) or by sample type (plasma, media, ENCODE). 
      # you might need to also seperate based on the how but if a window size that you want too! ex 1 kb vs 10kb, it wil change this for every data type in compute matrix
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/test2.csv"
      active: T
      settings:
        bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/1HG38_TSS+TES_ProteinCodingGenes.bed"
        bamCoverage_code: "bamCoverage"
        computeMatrix_code: "computeMatrix reference-point"
        plot_command: "-colorMap Blues"
        identifier: "hi"
    subsampled_k27_fwd_RPKM:
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/test.csv"
      active: F
      settings:
        bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/1HG38_TSS+TES_ProteinCodingGenes.bed"
        bamCoverage_code: "bamCoverage  bl /cluster/projects/scottgroup/people/sasha/reference/hg38-blacklist.v2.bed.gz \
        -p max --normalizeUsing RPKM -bs 1 --samFlagExclude 16 --extendReads --centerReads --samFlagInclude 64" #-b -o already specified
        computeMatrix_code: "reference-point -a 25000 -b 5000 --referencePoint TSS --skipZeros --missingDataAsZero -p max" #-S -R -o already specified
        plot_command: "-colorMap Blues" #-m -o already specified, need to specify plotProfile or plotHeatmap
        identifier: "subsampled"


