paths:
  dependencies:
    conda_env: deeptools-pipeline
data:
  base_path: /cluster/projects/scottgroup/people/lucas/deeptools-pipeline
  bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed" #directory to bed files of interest. Snakemake will run these seperately
  cohorts:
    subsampled_k27_fwd_RPKM_1M:
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/subsampled27_1M.csv"
      active: T
      settings:
        bamCoverage_code: "-bl /cluster/projects/scottgroup/people/sasha/reference/hg38-blacklist.v2.bed.gz \
        -p max --normalizeUsing RPKM -bs 1 --samFlagExclude 16 " #bamCoverage -b -o already specified
        computeMatrix_code: "reference-point -a 10000 -b 5000 --referencePoint TSS --skipZeros --missingDataAsZero -p max" #-S -R -o --samflagExclude --centreReads --samflagInclude already specified
        plot_command: "plotHeatmap --colorMap Blues" #-m -o already specified, NEED to specify plotProfile or plotHeatmap
        identifier: "refpoint_a10000b5000_TSS" #if want to change analysis for computematrix,change code and identifier
        single_ended: ["ENCODEk27downsample_1M"] #add sample names in list format that are single-ended


