paths:
  dependencies:
    conda_env: deeptools-pipeline
data:
  base_path: /cluster/projects/scottgroup/people/lucas/deeptools-pipeline
  cohorts:
    subsampled_k27_fwd_RPKM:
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/subsampled27.csv"
      active: T
      settings:
        bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/1HG38_TSS+TES_ProteinCodingGenes.bed"
        bamCoverage_code: "-bl /cluster/projects/scottgroup/people/sasha/reference/hg38-blacklist.v2.bed.gz \
        -p max --normalizeUsing RPKM -bs 1 --samFlagExclude 16 " #-b -o already specified
        computeMatrix_code: "reference-point -a 10000 -b 5000 --referencePoint TSS --skipZeros --missingDataAsZero -p max" #-S -R -o already specified
        plot_command: "plotHeatmap --colorMap Blues" #-m -o already specified, need to specify plotProfile or plotHeatmap
        identifier: "refpoint_a10000b5000_TSS" #if want to change analysis for computematrix,change code and identifier
        single_ended: ["ENCODEk27downsample"]
    subsampled_k27_fwd_noRPKM:
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/subsampled27.csv"
      active: T
      settings:
        bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/1HG38_TSS+TES_ProteinCodingGenes.bed"
        bamCoverage_code: "-bl /cluster/projects/scottgroup/people/sasha/reference/hg38-blacklist.v2.bed.gz \
        -p max --normalizeUsing None -bs 1 --samFlagExclude 16" #-b -o already specified
        computeMatrix_code: "reference-point -a 10000 -b 5000 --referencePoint TSS --skipZeros --missingDataAsZero -p max" #-S -R -o already specified
        plot_command: "plotHeatmap --colorMap Blues" #-m -o already specified, need to specify plotProfile or plotHeatmap
        identifier: "refpoint_a10000b5000_TSS"
        single_ended: ["ENCODEk27downsample"]
    subsampled_k4_fwd_RPKM:
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/subsampled4.csv"
      active: T
      settings:
        bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/1HG38_TSS+TES_ProteinCodingGenes.bed"
        bamCoverage_code: "-bl /cluster/projects/scottgroup/people/sasha/reference/hg38-blacklist.v2.bed.gz \
        -p max --normalizeUsing RPKM -bs 1 --samFlagExclude 16" #-b -o already specified
        computeMatrix_code: "reference-point -a 10000 -b 5000 --referencePoint TSS --skipZeros --missingDataAsZero -p max" #-S -R -o already specified
        plot_command: "plotHeatmap --colorMap Blues" #-m -o already specified, need to specify plotProfile or plotHeatmap
        identifier: "refpoint_a10000b5000_TSS"
        single_ended: ["ENCODEk4downsample"]
    subsampled_k4_fwd_noRPKM:
      samplesheet: "/cluster/home/t116306uhn/workflows/deeptools-pipeline/subsampled4.csv"
      active: T
      settings:
        bed_dir: "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/1HG38_TSS+TES_ProteinCodingGenes.bed"
        bamCoverage_code: "-bl /cluster/projects/scottgroup/people/sasha/reference/hg38-blacklist.v2.bed.gz \
        -p max --normalizeUsing None -bs 1 --samFlagExclude 16" #-b -o already specified
        computeMatrix_code: "reference-point -a 10000 -b 5000 --referencePoint TSS --skipZeros --missingDataAsZero -p max" #-S -R -o already specified
        plot_command: "plotHeatmap --colorMap Blues" #-m -o already specified, need to specify plotProfile or plotHeatmap
        identifier: "refpoint_a10000b5000_TSS"
        single_ended: ["ENCODEk4downsample"]


