#!/bin/sh
# properties = {"rule": "compute_matrix_cohort", "local": false, "input": ["/cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/plasmak27downsample_1M.bw", "/cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/mediak27.1downsample_1M.bw", "/cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/mediak27.2downsample_1M.bw", "/cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/ENCODEk27downsample_1M.bw"], "output": ["/cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/matrices/subsampled_k27_fwd_RPKM_1M_3UCSC_CpG_islands_plus_shores.bed_TSS.matrix.gz"], "wildcards": ["subsampled_k27_fwd_RPKM_1M", "3UCSC_CpG_islands_plus_shores.bed", "TSS"], "params": {"code": "reference-point -a 10000 -b 5000 --referencePoint TSS --skipZeros --missingDataAsZero -p max", "bed": "/cluster/projects/scottgroup/people/lucas/cfChIP-seq_Steven/4.Regions_bed/3UCSC_CpG_islands_plus_shores.bed"}, "log": [], "threads": 1, "resources": {"cpus": 2, "mem_mb": 25000, "time_min": 180}, "jobid": 2, "cluster": {}}
cd /cluster/home/t116306uhn/workflows/deeptools-pipeline && \
/cluster/home/t116306uhn/anaconda3/envs/deeptools-pipeline/bin/python -m snakemake /cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/matrices/subsampled_k27_fwd_RPKM_1M_3UCSC_CpG_islands_plus_shores.bed_TSS.matrix.gz --snakefile /cluster/home/t116306uhn/workflows/deeptools-pipeline/Snakefile \
--force -j --keep-target-files --keep-shadow --keep-remote \
--wait-for-files /cluster/home/t116306uhn/workflows/deeptools-pipeline/.snakemake/tmp.2dk61al_ /cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/plasmak27downsample_1M.bw /cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/mediak27.1downsample_1M.bw /cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/mediak27.2downsample_1M.bw /cluster/projects/scottgroup/people/lucas/deeptools-pipeline/results/subsampled_k27_fwd_RPKM_1M/bw/ENCODEk27downsample_1M.bw --latency-wait 5 \
--benchmark-repeats 1 \
--force-use-threads --wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
  -p --nocolor \
--notemp --quiet --no-hooks --nolock --printshellcmds  --force-use-threads  --allowed-rules compute_matrix_cohort  && touch "/cluster/home/t116306uhn/workflows/deeptools-pipeline/.snakemake/tmp.2dk61al_/2.jobfinished" || (touch "/cluster/home/t116306uhn/workflows/deeptools-pipeline/.snakemake/tmp.2dk61al_/2.jobfailed"; exit 1)

